name: CI/CD Pipeline for SQLWithIndexing

# Trigger workflow khi push hoặc pull request vào branch SQLWithIndexing
on:
  push:
    branches:
      - SQLWithIndexing
  pull_request:
    branches:
      - SQLWithIndexing

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn từ branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Cài đặt phụ thuộc từ requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t pdf-processor:latest .

      # Chạy container để test (giả lập kiểm tra)
      - name: Test Docker container
        run: |
          docker run --rm pdf-processor:latest uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Chờ server khởi động
          curl http://localhost:8000 || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test  # Chỉ chạy nếu build-and-test thành công
    if: github.event_name == 'push'  # Chỉ deploy khi push, không phải pull request
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Login vào Docker Hub (nếu muốn push image lên registry)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build và push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }}

      # Deploy (ví dụ: cập nhật tag trong Helm hoặc deploy lên server)
    #   - name: Deploy to Server
    #     run: |
    #       echo "Deploying image ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }}"
    #       # Thêm lệnh deploy tại đây (ví dụ: SSH vào server, hoặc dùng kubectl nếu dùng Kubernetes)