name: CI/CD Pipeline for SQLWithIndexing

on:
  push:
    branches:
      - SQLWithIndexing
  pull_request:
    branches:
      - SQLWithIndexing

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: pdf_processor
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t pdf-processor:latest .

      - name: Test Docker container
        run: |
          docker run --rm -d --name pdf-app \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_NAME=pdf_processor \
            -e DB_USER=postgres \
            -e DB_PASSWORD=123456 \
            --network host \
            -p 8000:8000 \
            pdf-processor:latest
          sleep 10
          curl http://localhost:8000 || exit 1
          docker stop pdf-app

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }}
