name: CI/CD Pipeline for SQLWithIndexing

on:
  push:
    branches:
      - SQLWithIndexing
  pull_request:
    branches:
      - SQLWithIndexing

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: pdf_processor
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - run: |
          docker build -t pdf-processor:latest .
          docker run -d --name pdf-app \
            -e DB_HOST=postgres \
            -e DB_PORT=5432 \
            -e DB_NAME=pdf_processor \
            -e DB_USER=postgres \
            -e DB_PASSWORD=123456 \
            --network host \
            -p 8000:8000 \
            pdf-processor:latest
          sleep 5
          curl -s http://localhost:8000 || exit 1
          docker stop pdf-app

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }}
      - name: Deploy to EC2 with Nginx
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > ec2_key.pem
          chmod 400 ec2_key.pem
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            echo "Step 1: Docker login"
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} || exit 1

            echo "Step 2: Create network"
            docker network create pdf-network || true

            echo "Step 3: Prepare volume"
            sudo mkdir -p /data/postgres-data && sudo chown 999:999 /data/postgres-data && sudo chmod 700 /data/postgres-data

            echo "Step 4: Stop and remove old containers"
            docker stop postgres-db pdf-app nginx || true
            docker rm postgres-db pdf-app nginx || true

            echo "Step 5: Run PostgreSQL"
            docker run -d --name postgres-db \
              --network pdf-network \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e POSTGRES_DB=pdf_processor \
              -v /data/postgres-data:/var/lib/postgresql/data \
              postgres:13 || exit 1
            sleep 5

            echo "Step 6: Run pdf-app"
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }} || exit 1
            docker run -d --name pdf-app \
              --network pdf-network \
              -e DB_HOST=postgres-db \
              -e DB_PORT=5432 \
              -e DB_NAME=pdf_processor \
              -e DB_USER=postgres \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/pdf-processor:${{ github.sha }} || exit 1
            sleep 10

            echo "Step 7: Check DB connection"
            docker exec pdf-app python -c "import psycopg2; conn = psycopg2.connect(host='postgres-db', port=5432, dbname='pdf_processor', user='postgres', password='${{ secrets.DB_PASSWORD }}'); conn.close()" || exit 1

            echo "Step 8: Create Nginx config"
            echo "server { listen 80; server_name _; client_max_body_size 100M; location / { proxy_pass http://pdf-app:8000; proxy_set_header Host \"\$host\"; proxy_set_header X-Real-IP \"\$remote_addr\"; proxy_set_header X-Forwarded-For \"\$proxy_add_x_forwarded_for\"; proxy_set_header X-Forwarded-Proto \"\$scheme\"; }}" > /tmp/nginx.conf

            echo "Step 9: Run Nginx"
            docker run -d --name nginx \
              --network pdf-network \
              -v /tmp/nginx.conf:/etc/nginx/conf.d/default.conf \
              -p 80:80 \
              nginx:alpine || exit 1
          EOF
          rm ec2_key.pem